import Head from "next/head";

export default function Title({ title }) {
  return (
    <Head>
      <title>Luxury Living - {title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
